apiVersion: v2
name: loki
description: A Helm chart for Kubernetes

type: application
version: 0.1.18
appVersion: "1.17.0"

dependencies:
  - name: loki
    repository: https://grafana.github.io/helm-charts
    # version: 2.13.3
    version: 5.41.2
