apiVersion: v2
name: loki
description: A Helm chart for Kubernetes

type: application
version: 0.1.9
appVersion: "1.16.0"

dependencies:
  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: 2.13.3
