loki:
  loki:
    tracing:
      enabled: true
    auth_enabled: false

    # TODO this is an abomination.
    # a SC need to be created for loki so this can be removed.
    podSecurityContext:
      fsGroup: 0
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    containerSecurityContext:
      readOnlyRootFilesystem: false
    # podSecurityContext:
    #   fsGroup: 10001
    #   runAsGroup: 10001
    #   runAsNonRoot: true
    #   runAsUser: 10001
    # containerSecurityContext:
    #   readOnlyRootFilesystem: false
    #   capabilities:
    #     drop:
    #       - ALL


  test:
    enabled: false

  write:
    replicas: 0

  read:
    replicas: 0

  backend:
    replicas: 0

  singleBinary:
    replicas: 1
    # This needs work, have a look at this:
    # https://github.com/grafana/loki/pull/4920
    targetModule: read
    persistence: 
      enabled: false
  ingress:
    enabled: false
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    # ingressClassName: nginx
    ingressClassName: public
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: loki.nextjs-grpc.utkusarioglu.com
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  gateway:
    enabled: false

  monitoring:
    dashboards:
      enabled: false
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
    lokiCanary:
      enabled: false

  # tableManager:
  #   enabled: true
  #   resources: {}
  #   extraVolumes:
  #     - name: data
  #       emptyDir: {}
  #   extraVolumeMounts:
  #     - name: data
  #       mountPath: /var/loki

  # storage:
  #   type: filesystem
  #   filesystem:
  #     chunks_directory: /var/loki/chunks
  #     rules_directory: /var/loki/rules
